// <auto-generated />
namespace Library.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addauthorIdtobooks_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addauthorIdtobooks_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201708192134420_add-authorId-to-books_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
